name: Check Semantic Versioning
on:
  - pull_request

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary to compare with the main branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Check version bump
        run: |
          # Fetch VERSION file from the main branch
          OLD_VERSION=$(git show origin/main:VERSION)
          # Read VERSION file from the current branch
          NEW_VERSION=$(cat VERSION)
          
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
          
          # Run the version comparison Python script
          python .github/workflows/version_check.py "$OLD_VERSION" "$NEW_VERSION"

